### ISSUE TITLE
Providing an IPS patch for end-users

### ISSUE THREAD

**Issue by niuus** [jordanbarkley/Ninja-Gaiden-Trilogy#1]
Any chance? It would be great.

**Comment by JoshuaPettus** [comment]
Here is one I made with flips after I got it working. 
[ninja.zip](https://github.com/jordanbarkley/Ninja-Gaiden-Trilogy/files/5198838/ninja.zip)

Uses regular unheaderd rom (.sfc)

**Comment by jordanbarkley** [comment]
I didn't know there was interest in this! Thank you @JoshuaPettus
