### ISSUE TITLE
Pressing L and R by mistake changes layout

### ISSUE THREAD

**Issue by Nashismo** [jordanbarkley/Ninja-Gaiden-Trilogy#2]
Dear Jordan:

This hack is awesome, but the only problem I am facing is that sometimes I press L or R by mistake and I change the button layout by accident.

Could you make it so, that the layout is always changed? (as in Y=slash, B=jump) or maybe to change the layout you could use Select+R for example? This button combination would make it almost imposible to hit by mistake.

My most sincere thanks Jordan!

**Comment by jordanbarkley** [comment]
@Nashismo I did the Select + L/R thing quickly. No means to test at the moment but it should work just fine

**Comment by Nashismo** [comment]
Thank you so much Jordan! I will be testing, but like you said, it should work just fine :)

Thanks again!
